name: tempalteflutter
description:

publish_to:

version: 1.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  modal_progress_hud_nsn: ^0.5.1
  share_plus:
  path_provider:
  win32: ^5.7.2
  bloc: ^8.1.2
  webview_flutter: ^4.2.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  font_awesome_flutter: ^10.5.0
  country_code_picker: ^3.0.0
  image_cropper: ^5.0.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.1.12
  intl: ^0.18.1
  page_indicator: ^0.4.1
  fluttertoast: ^8.2.2
  bottom_navy_bar: ^6.0.0
  persistent_bottom_nav_bar: ^5.0.2
  sticky_headers: ^0.3.0+2
  percent_indicator: ^4.2.3
  flutter_circle_color_picker:
  scroll_page_view: ^1.0.2
  pinput: ^3.0.1
  image_picker: ^0.8.7+5
  permission_handler: ^11.3.0
  geolocator:
  geocoding: ^3.0.0
  firebase_core:
  firebase_messaging:
  dartz:
  sms_autofill: ^2.4.1
  flutter_svg:
  hive_flutter:
  flutter_local_notifications: ^17.2.2
  shimmer: ^2.0.0


dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/cname/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-RegularItalic.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-LightItalic.ttf
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-ThinItalic.ttf
